#!/bin/sh

DEVICE=/dev/sr1
# the the number of args > 0 and isn't then pass them to the command
# else print the idiot message

if [ $# -gt 0 ]; then
    umount $DEVICE
    cdrdao read-cd --datafile $1.bin --driver generic-mmc:0x20000 --device $DEVICE --read-raw $1.toc
    toc2cue $1.toc $1.cue
    rm $1.toc
    eject $DEVICE
else
	echo "Usage: $0 filename"
fi
