#!/bin/sh
# blanks a CD-RW

DRIVE=/dev/cdrw
# fixup for case's multiple drive layout - use the newer,
# better drive for burns, which is drive "1";
if [ "`hostname`" = "case" ]; then
    DRIVE=$DRIVE"1"
elif [ "`hostname`" = "hiro" ]; then
    DRIVE="/dev/sr1";
fi

BLANK=fast
if [ "`basename $0`" = "fullblank" ]; then
    BLANK=all
fi

wodim -v dev=$DRIVE blank=$BLANK $@

