#!/bin/bash

BASEDIR=/media/matt/PHONE

PICS=$BASEDIR/DCIM/100KYCRA/

cp -a ~/.keepassx/* $BASEDIR/keepassx/.
cp -a ~/.ssh/id_* $BASEDIR/ssh/.
echo pulling pics
rsync -aLh --inplace "$PICS" "$HOME/workspace/pics/photos/new"
echo pushing music
rsync -aLh --inplace --delete "$HOME/music/" "$BASEDIR/Music"

echo moving pics to gallery
mv "$PICS"/* "$BASEDIR/pics/."
echo done

echo Is it time to run a backup OpenAndroidBackup?
echo If so, do it, then plug it in to the computer and run backup_phone.
echo Bye!



