#!/bin/bash

# Default assumes SD card 
BASEDIR=/media/$USER/TABLET

echo keepass....
mkdir -p "$BASEDIR/keepassx"
cp -a ~/.keepassx/* "$BASEDIR/keepassx/."
mkdir -p "$BASEDIR/ssh"
cp -a ~/.ssh/id_* "$BASEDIR/ssh/."
echo pulling pics
rsync -aLh --inplace "$BASEDIR/DCIM/Camera/" "$HOME/workspace/pics/photos/new"
echo moving pics to gallery
mv "$BASEDIR/DCIM/Camera/*" "$BASEDIR/pics/."
echo rpgs
rsync -aLh --inplace --delete "$HOME/gaming/rpgs/" "$BASEDIR/rpgs"
# Not always mounted
# echo reading
# rsync -aLh --inplace --delete "$HOME/pub/reading/" "$BASEDIR/reading"
echo blaster_magazine
rsync -aLh --inplace --delete "$HOME/gaming/blaster_magazine/" "$BASEDIR/blaster_magazine"
echo bexims_bazar
rsync -aLh --inplace --delete "$HOME/gaming/bexims_bazar/" "$BASEDIR/bexims_bazar"
echo terrain_essentials
rsync -aLh --inplace --delete "$HOME/gaming/terrain_essentials/" "$BASEDIR/terrain_essentials"
echo armies_legions_and_hordes
rsync -aLh --inplace --delete "$HOME/gaming/armies_legions_and_hordes/" "$BASEDIR/armies_legions_and_hordes"
echo boardgames
rsync -aLh --inplace --delete "$HOME/gaming/boardgames/" "$BASEDIR/boardgames"
echo ccgs
rsync -aLh --inplace --delete "$HOME/gaming/ccgs/" "$BASEDIR/ccgs"
echo cards
rsync -aLh --inplace --delete "$HOME/gaming/cards/" "$BASEDIR/cards"
echo dice
rsync -aLh --inplace --delete "$HOME/gaming/dice/" "$BASEDIR/dice"
echo maps
rsync -aLh --inplace --delete "$HOME/gaming/maps/" "$BASEDIR/maps"
echo mine
rsync -aLh --inplace --delete "$HOME/gaming/mine/" "$BASEDIR/mine"
echo minis
rsync -aLh --inplace --delete "$HOME/gaming/minis/" "$BASEDIR/minis"
echo molds
rsync -aLh --inplace --delete "$HOME/gaming/molds/" "$BASEDIR/molds"
echo done

echo Is it time to run a backup with adb?
echo If so, do it, then plug it in to the computer and run backup_tablet.
echo Bye!
