#!/bin/bash

usage() {
    echo "$0 - sync music to target"
    echo "Usage: $0 target directory"
}

if [ $# -lt 1 ]; then
    usage
    exit
fi

if [[ $1 == "--help" ]]; then
    usage
    exit
fi

rsync -aLh --inplace --delete $HOME/music/ $1
